---
- debug: msg={{credentials}}

- name: create pwsswd file
  copy: src=passwd dest=/etc/squid3/passwd

- name:       create user with password
  command:    htpasswd -bm /etc/squid3/passwd {{ item.login }} {{ item.password }}
  with_items: credentials

- name: ensure correct access rights
  file:
    path: /etc/squid3/passwd
    mode: 0644
